# Hugo's config file

baseurl = "https://www.khalidjhosein.net/"
languagecode = "en-US"
title = "Khalid J Hosein"
theme = "cocoa-eh-hugo-theme"
builddrafts = true
canonifyurls = true
contentdir = "content"
layoutdir = "layouts"
publishdir = "public"
author = "Khalid J Hosein"
disqusshortname = ""
pluralizelisttitles = false


[permalinks]
  blog = "/:year/:month/:slug/"
  #blog = "blog/:slug/"
  #blog/2015 = "/:year/:month/:slug/"  # doesn't work.

[params]
dateform = "2 Jan 2006"
dateformfull = "Mon 2 Jan 2006 15:04:05 MST"
description = "The blog of Khalid J Hosein"
copyright = "Copyright © 2013-2024 Khalid J Hosein"
logofile = "img/circuit.png"
faviconfile = "img/letter-k.png"
highlightjs = true
progressively = true
lang = "en"
github = "kjhosein"
email = "kjh%2Bblog@exocloudventures.com?subject=Contact%20via%20Blog"
linkedin = "khalidhosein"
twitter = "kjhosein"
social_banner = "img/banner.png"
posts_navigation = true
small_banner_logo = false
latestpostcount = 5
usesmallsummarycard = true
exclude_headings = "Detailed Cloud and DevOps Experience report, 2013-"

[build.processing]
    skip_processing = true

[services]
  [services.googleAnalytics]
    ID = 'G-RTJ5LJSVHB'
